var tg=window.tg={};tg.exportSymbol=function(a,c){var b=a.split("."),e=window,d;for(d=0;d<b.length-1;d+=1)e=e[b[d]];e[b[b.length-1]]=c};var config=window.tgConfig||{},extend=function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},config=extend(config,{namespace:"tg.objects"});(function(){var a=config.namespace.split("."),c=window,b;for(b=0;b<a.length;b+=1)void 0===c[a[b]]&&(c[a[b]]={}),c=c[a[b]];tg.generatedNamespace=c})();tg.getGeneratedNamespaceObj=function(){return tg.generatedNamespace};
tg.exportSymbol("tg",tg);tg.RowState={INVALID:0,UNCHANGED:2,ADDED:4,DELETED:8,MODIFIED:16};tg.exportSymbol("tg.RowState",tg.RowState);
tg.DateParser=function(){this.deserialize=function(a){var c;"string"===typeof a&&0===a.indexOf("/Date(")&&(c=0,-1===a.indexOf("-")&&(c=new Date,c=c.getTimezoneOffset()),a=new Date(parseInt(a.substr(6))),0<c&&a.setMinutes(a.getMinutes()+c));return a};this.serialize=function(a){return"/Date("+Date.UTC(a.getFullYear(),a.getMonth(),a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds(),0)+")/"}};tg.getType=function(a){return tg.getGeneratedNamespaceObj()[a]};
tg.clearTypes=function(){tg.generatedNamespace={}};tg.onError=ko.observable({});tg.onError.subscribe(function(a){throw JSON.stringify(a);});tg.isArray=function(a){a=ko.utils.unwrapObservable(a);return!a?!1:a.isArray||"[object Array]"===Object.prototype.toString.call(a)};tg.objectKeys=Object.keys||function(a){var c,b=[];for(c in a)b.push(c);return b};
tg.isTiraggoCollection=function(a){var c=!1;void 0!==a&&void 0!==a.tg?void 0!==a.tg.___TiraggoCollection___&&(c=!0):tg.isArray(a)&&0<a.length&&a[0].hasOwnProperty("RowState")&&(c=!0);return c};tg.isTiraggoEntity=function(a){var c=!1;void 0!==a&&(void 0!==a.tg&&void 0!==a.tg.___TiraggoEntity___)&&(c=!0);return c};tg.isTiraggoLazyLoader=function(a){var c=!1;void 0!==a&&(void 0!==a.tg&&void 0!==a.tg.___TiraggoLazyLoad___)&&(c=!0);return c};tg.exportSymbol("tg.isTiraggoCollection",tg.isTiraggoCollection);
var utils={dateParser:new tg.DateParser,copyDataIntoEntity:function(a,c){var b,e;if(a&&c){for(b in a)if(c.hasOwnProperty(b)&&(!a.tgTypeDefs||!a.tgTypeDefs[b]))if(e=c[b],"string"===typeof e&&(e=utils.dateParser.deserialize(e)),ko.isObservable(a[b])||ko.isComputed(a[b]))a[b](e);else a[b]=e;return a}},extend:function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},addPropertyChangedHandlers:function(a,c){var b=a[c];ko.isObservable(b)&&(!(b instanceof Array)&&b.__ko_proto__!==ko.dependentObservable)&&
b.subscribe(function(b){var d;!1===a.tg.ignorePropertyChanged&&(d=a.tgColumnMap[c],1===d&&(d=c),d=d||c,-1===ko.utils.arrayIndexOf(a.ModifiedColumns(),d)&&(a.tg.originalValues[c]||(a.tg.originalValues[c]=b),"RowState"!==c&&(a.ModifiedColumns.push(d),a.RowState()!==tg.RowState.MODIFIED&&a.RowState()!==tg.RowState.ADDED&&a.RowState(tg.RowState.MODIFIED))))},a,"beforeChange")},startTracking:function(a){var c,b;a.hasOwnProperty("RowState")?ko.isObservable(a.RowState)||(a.RowState=ko.observable(a.RowState)):
a.RowState=ko.observable(tg.RowState.ADDED);a.hasOwnProperty("ModifiedColumns")?a.ModifiedColumns([]):a.ModifiedColumns=ko.observableArray();for(c in a)"ModifiedColumns"!==c&&("__type"!==c&&"tgExtendedData"!==c&&"tg"!==c)&&(b=a[c],b instanceof Array||a.hasOwnProperty(c)&&ko.isObservable(b)&&utils.addPropertyChangedHandlers(a,c));return a},expandExtraColumns:function(a,c){var b,e,d=c||!1;if(a.tgExtendedData&&tg.isArray(a.tgExtendedData)){b=ko.isObservable(a.tgExtendedData)?a.tgExtendedData():a.tgExtendedData;
for(e=0;e<b.length;e+=1)if(ko.isObservable(a[b[e].Key]))a[b[e].Key](b[e].Value);else a[b[e].Key]=d?ko.observable(b[e].Value):b[e].Value;a.tgExtendedData=[]}return a},getDirtyGraph:function(a,c,b){var e,d,f,g;if(void 0===c&&!a.isDirtyGraph())return null;if(tg.isTiraggoEntity(a))for(e in tg.isArray(b)?(d=a.prepareForJSON(),b.push(d),b=d):b=a.prepareForJSON(),void 0===c&&(c=b),a.tgTypeDefs){if(void 0!==a[e]&&a[e].isDirtyGraph()){f=a[e].prepareForJSON();b[e]=[];for(g=0;g<f.length;g+=1)d=f[g],tg.utils.getDirtyGraph(d,
c,b[e])}}else{c=[];f=a.prepareForJSON();for(g=0;g<f.length;g+=1)d=f[g],tg.utils.getDirtyGraph(d,c,c)}return c}};utils.newId=function(){var a=(new Date).getTime();return function(){return a+=1}}();tg.utils=utils;tg.exportSymbol("tg.extend",tg.extend);tg.exportSymbol("tg.startTracking",tg.startTracking);tg.exportSymbol("tg.getDirtyGraph",tg.getDirtyGraph);tg.PagerFilterCriteria=function(){this.operation=this.criteria2=this.criteria1=this.column=null;this.conjuction="AND"};
tg.PagerSortCriteria=function(){this.column=null;this.direction="ASC"};tg.PagerRequest=function(){this.getTotalRows=!0;this.totalRows=0;this.pageSize=20;this.pageNumber=1;this.filterCriteria=this.sortCriteria=null};
tg.tgLazyLoader=function(a,c){return function(){var b;if(0===arguments.length){if(void 0===b){b=a.createObjectFromType(a.tgTypeDefs[c]);if(void 0===b)throw"Please include the JavaScript class file for the '"+type+"'";b.load({route:a.tgRoutes[c],data:a.tgPrimaryKeys()})}a[c]=b;return"collection"===a.tgRoutes[c].response?b():b}}};tg.tgLazyLoader.fn={__ko_proto__:ko.observable,isDirty:function(){return!1},isDirtyGraph:function(){return!1},subscribe:function(){}};
tg.defineLazyLoader=function(a,c){var b=function(){return(new tg.tgLazyLoader(a,c))()};ko.utils.extend(b,tg.tgLazyLoader.fn);b.tg={};b.tg.___TiraggoLazyLoader___=!0;return b};
tg.TiraggoEntity=function(){var a=[];this.customize=function(c){a.push(c);return this};this.init=function(){var c=this;c.tg.___TiraggoEntity___=tg.utils.newId();c.tg.ignorePropertyChanged=!1;c.tg.originalValues={};c.tg.isLoading=ko.observable(!1);tg.utils.startTracking(c);ko.utils.arrayForEach(a,function(a){a&&a.call(c)});this.isDirty=ko.computed(function(){return c.RowState()!==tg.RowState.UNCHANGED});this.isDirtyGraph=function(){var a,e=!1;if(c.RowState()!==tg.RowState.UNCHANGED)return!0;for(a in this.tgTypeDefs)if(void 0!==
this[a]&&(e=this[a].isDirtyGraph(),!0===e))break;return e}};this.createObjectFromEsTypeDef=function(a){var b;this.tgTypeDefs&&this.tgTypeDefs[a]&&(a=tg.getType(this.tgTypeDefs[a]))&&(b=new a);return b};this.createObjectFromType=function(a){var b;(a=tg.getType(a))&&(b=new a);return b};this.prepareForJSON=function(){var a=this,b={};ko.utils.arrayForEach(tg.objectKeys(this),function(e){var d;switch(e){case "tg":case "tgTypeDefs":case "tgRoutes":case "tgColumnMap":case "tgExtendedData":case "tgPrimaryKeys":break;
case "RowState":b.RowState=ko.utils.unwrapObservable(a.RowState);break;case "ModifiedColumns":b.ModifiedColumns=ko.utils.unwrapObservable(a.ModifiedColumns);break;default:if(void 0!==a.tgColumnMap[e]){if(d=ko.utils.unwrapObservable(a[e]),null===d||"function"!==typeof d&&void 0!==d)b[e]=null!==d&&d instanceof Date?utils.dateParser.serialize(d):d}else if(d=a[e],tg.isTiraggoCollection(d)&&a[e].isDirty()){d=d();var f=[];ko.utils.arrayForEach(d,function(a){f.push(a.prepareForJSON())});b[e]=f}}});return b};
this.populateEntity=function(a){var b,e,d;this.tg.ignorePropertyChanged=!0;try{for(b in this.hasOwnProperty("ModifiedColumns")?this.ModifiedColumns([]):this.ModifiedColumns=ko.observableArray(),this.tg.originalValues={},tg.utils.copyDataIntoEntity(this,a),tg.utils.expandExtraColumns(this,!0),a)if(a.hasOwnProperty(b)&&this.tgTypeDefs&&this.tgTypeDefs[b])if(e=tg.getType(this.tgTypeDefs[b]))if(d=new e,d.tg.hasOwnProperty("___TiraggoCollection___")?d.populateCollection(a[b]):d.populateEntity(a[b]),tg.isTiraggoCollection(this[b]))this[b](d());
else this[b]=d;else tg.isArray(a[b])?(this[b]=a[b],ko.utils.arrayForEach(this[b],function(){})):this[b]=a[b]}finally{this.tg.ignorePropertyChanged=!1}};this.applyDefaults=function(){};this.acceptChanges=function(){this.tg.originalValues={};this.ModifiedColumns([]);this.tg.ignorePropertyChanged=!0;this.RowState(tg.RowState.UNCHANGED);this.tg.ignorePropertyChanged=!1};this.rejectChanges=function(){var a;if(this.tg.originalValues){this.tg.ignorePropertyChanged=!0;for(a in this.tg.originalValues)this[a](this.tg.originalValues[a]);
this.ModifiedColumns([]);this.tg.originalValues={};this.tg.ignorePropertyChanged=!1}};this.markAsDeleted=function(){this.hasOwnProperty("RowState")?this.RowState()!==tg.RowState.DELETED&&this.RowState(tg.RowState.DELETED):this.RowState=ko.observable(tg.RowState.DELETED);this.hasOwnProperty("ModifiedColumns")&&this.ModifiedColumns.removeAll()};this.load=function(a){var b={},e=this;e.tg.isLoading(!0);b.wasLoaded=!1;b.state=a.state;a.async=void 0!==a.success||void 0!==a.error?!0:!1;a.route&&(a.url=a.route.url||
this.tgRoutes[a.route].url,a.type=a.route.method||this.tgRoutes[a.route].method);var d=a.success,f=a.error;a.success=function(a){void 0!==a&&null!==a&&(b.wasLoaded=!0,e.populateEntity(a));d&&d.call(e,a,b);e.tg.isLoading(!1)};a.error=function(a,c){f&&f.call(e,a,c,b);e.tg.isLoading(!1)};tg.dataProvider.execute(a);!1===a.async&&e.tg.isLoading(!1);return b.wasLoaded};this.loadByPrimaryKey=function(a,b,e,d){var f={route:this.tgRoutes.loadByPrimaryKey};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]?
tg.utils.extend(f,arguments[0]):(f.data=a,f.success=b,f.error=e,f.state=d);return this.load(f)};this.save=function(a,b,e){var d=this;d.tg.isLoading(!0);var f={success:a,error:b,state:e,route:d.tgRoutes.commit};switch(d.RowState()){case tg.RowState.ADDED:f.route=d.tgRoutes.create||f.route;break;case tg.RowState.MODIFIED:f.route=d.tgRoutes.update||f.route;break;case tg.RowState.DELETED:f.route=d.tgRoutes["delete"]||f.route}1===arguments.length&&(arguments[0]&&"object"===typeof arguments[0])&&tg.utils.extend(f,
arguments[0]);f.async=void 0!==f.success||void 0!==f.error?!0:!1;f.data=tg.utils.getDirtyGraph(d);if(null===f.data)!0===f.async&&f.success(null,f.state),d.tg.isLoading(!1);else{f.route&&(f.url=f.route.url,f.type=f.route.method);var g=f.success,h=f.error;f.success=function(a,b){d.populateEntity(a);g&&g.call(d,a,b.state);d.tg.isLoading(!1)};f.error=function(a,b,c){h&&h.call(d,a,b,c.state);d.tg.isLoading(!1)};tg.dataProvider.execute(f);!1===f.async&&d.tg.isLoading(!1)}}};
tg.exportSymbol("tg.TiraggoEntity",tg.TiraggoEntity);tg.exportSymbol("tg.TiraggoEntity.populateEntity",tg.TiraggoEntity.populateEntity);tg.exportSymbol("tg.TiraggoEntity.markAsDeleted",tg.TiraggoEntity.markAsDeleted);tg.exportSymbol("tg.TiraggoEntity.load",tg.TiraggoEntity.load);tg.exportSymbol("tg.TiraggoEntity.loadByPrimaryKey",tg.TiraggoEntity.loadByPrimaryKey);tg.exportSymbol("tg.TiraggoEntity.save",tg.TiraggoEntity.save);
tg.TiraggoEntityCollection=function(){var a=ko.observableArray([]);a.tg={};ko.utils.extend(a,tg.TiraggoEntityCollection.fn);a.tg.___TiraggoCollection___=tg.utils.newId();a.tg.deletedEntities=new ko.observableArray;a.tg.deletedEntities([]);a.tg.isLoading=ko.observable(!1);return a};
tg.TiraggoEntityCollection.fn={filter:function(a){var c=this();return ko.utils.arrayFilter(c,a)},prepareForJSON:function(){var a=[];ko.utils.arrayForEach(this(),function(c){c.isDirtyGraph()&&a.push(c)});ko.utils.arrayForEach(this.tg.deletedEntities(),function(c){c.RowState()!==tg.RowState.ADDED&&a.push(c)});return a},acceptChanges:function(){ko.utils.arrayForEach(this(),function(a){a.RowState()!==tg.RowState.UNCHANGED&&a.acceptChanges()});this.tg.deletedEntities([])},rejectChanges:function(){var a=
[],c=0,b=0,e;ko.utils.arrayForEach(this.tg.deletedEntities(),function(d){d.RowState()===tg.RowState.ADDED?(a[c]=b,c+=1):d.rejectChanges();b+=1});if(0<a.length)for(b=a.length-1;0<=b;b--)this.tg.deletedEntities.splice(a[b],1);a=[];ko.utils.arrayForEach(this(),function(b){switch(b.RowState()){case tg.RowState.MODIFIED:b.rejectChanges();break;case tg.RowState.ADDED:a.push(b)}});if(0<a.length)for(e=0;e<a.length;e++)b=ko.utils.arrayIndexOf(this(),a[e]),0<=b&&this.splice(b,1);0<this.tg.deletedEntities().length&&
(e=this().concat(this.tg.deletedEntities()),this(e));this.tg.deletedEntities([])},markAllAsDeleted:function(){var a,c,b,e;this.tg.deletedEntities(this.splice(0,this().length));b=this.tg.deletedEntities;e=b().length;for(a=0;a<e;a+=1)c=b()[a],c.RowState()===tg.RowState.UNCHANGED&&(c.hasOwnProperty("RowState")?c.RowState()!==tg.RowState.DELETED&&c.RowState(tg.RowState.DELETED):c.RowState=ko.observable(tg.RowState.DELETED),c.hasOwnProperty("ModifiedColumns")&&c.ModifiedColumns.removeAll())},markAsDeleted:function(a){var c,
b,e,d;b=[];if(!arguments)throw Error("The entitiesOrEntityToDelete cannot be null or undefined.");if(tg.isArray(a)){if(b=ko.utils.unwrapObservable(a),0===b.length)throw Error("The array passed in to markAsDeleted.markAsDeleted() cannot be empty.");}else for(c=0;c<arguments.length;c++)if(tg.isTiraggoEntity(arguments[c]))b.push(arguments[c]);else throw Error("Invalid type passed in to markAsDeleted.markAsDeleted()");c=this.tg.deletedEntities().concat(b);this.tg.deletedEntities(c);this.removeAll(b);
e=this.tg.deletedEntities;d=e().length;for(c=0;c<d;c+=1)b=e()[c],b.RowState()===tg.RowState.UNCHANGED&&(b.hasOwnProperty("RowState")?b.RowState()!==tg.RowState.DELETED&&b.RowState(tg.RowState.DELETED):b.RowState=ko.observable(tg.RowState.DELETED),b.hasOwnProperty("ModifiedColumns")&&b.ModifiedColumns.removeAll())},populateCollection:function(a){var c=this.tg.entityTypeName,b,e=[],d=this.createEntity,f;c&&(b=tg.getType(c));a&&tg.isArray(a)&&(ko.utils.arrayForEach(a,function(a){f=d(a,b);void 0!==f&&
null!==f&&e.push(f)}),this(e))},createEntity:function(a,c){var b;b=c;c||(b=this.tg.entityTypeName,b=tg.getType(b));b?(b=new b,b.populateEntity(a)):b=a;return b},addNew:function(){var a=null,c=this.tg.entityTypeName;c&&(a=tg.getType(c),a=new a,this.push(a));return a},load:function(a){var c=this;c.tg.isLoading(!0);a.async=void 0!==a.success||void 0!==a.error?!0:!1;a.route&&(a.url=a.route.url||this.tgRoutes[a.route].url,a.type=a.route.method||this.tgRoutes[a.route].method);var b=a.success,e=a.error;
a.success=function(a,e){c.populateCollection(a);b&&b.call(c,a,e.state);c.tg.isLoading(!1)};a.error=function(a,b,g){e&&e.call(c,a,b,g.state);c.tg.isLoading(!1)};tg.dataProvider.execute(a);!1===a.async&&c.tg.isLoading(!1)},loadAll:function(a,c,b){var e={route:this.tgRoutes.loadAll};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]?tg.utils.extend(e,arguments[0]):(e.success=a,e.error=c,e.state=b);this.load(e)},save:function(a,c,b){var e=this;e.tg.isLoading(!0);var d={success:a,error:c,
state:b,route:e.tgRoutes.commit};1===arguments.length&&(arguments[0]&&"object"===typeof arguments[0])&&tg.utils.extend(d,arguments[0]);d.async=void 0!==d.success||void 0!==d.error?!0:!1;d.data=tg.utils.getDirtyGraph(e);if(null===d.data){if(!1===d.async){e.tg.isLoading(!1);return}d.success(null,d)}d.route&&(d.url=d.route.url,d.type=d.route.method);var f=d.success,g=d.error;d.success=function(a,b){e.tg.deletedEntities([]);e.populateCollection(a);f&&f.call(e,a,b.state);e.tg.isLoading(!1)};d.error=function(a,
b,c){g&&g.call(e,a,b,c.state);e.tg.isLoading(!1)};tg.dataProvider.execute(d);!1===d.async&&e.tg.isLoading(!1)}};tg.exportSymbol("tg.TiraggoEntityCollection",tg.TiraggoEntityCollection);tg.exportSymbol("tg.TiraggoEntityCollection.markAllAsDeleted",tg.TiraggoEntityCollection.markAllAsDeleted);tg.exportSymbol("tg.TiraggoEntityCollection.loadAll",tg.TiraggoEntityCollection.loadAll);tg.exportSymbol("tg.TiraggoEntityCollection.load",tg.TiraggoEntityCollection.load);
tg.exportSymbol("tg.TiraggoEntityCollection.save",tg.TiraggoEntityCollection.save);tg.defineEntity=function(a,c){var b="string"!==typeof a,e=b?a:c,d=function(a){this.tg={};e.call(this);this.applyDefaults();this.init();a&&this.populateEntity(a)};d.prototype=new tg.TiraggoEntity;b||(tg.generatedNamespace[a]=d);return d};tg.exportSymbol("tg.defineEntity",tg.defineEntity);
tg.defineCollection=function(a,c){var b="string"!==typeof a,e=b?a:c,d=function(a){var b=new tg.TiraggoEntityCollection;b.tg.entityTypeName=e;this.init.call(b);a&&b.populateCollection(a);return b};d.prototype=new function(){var a=this,b=[];this.init=function(){var c=this;ko.utils.arrayForEach(b,function(a){a.call(c)});for(var d in a)a.hasOwnProperty(d)&&("init"!==d&&"customize"!==d)&&(c[d]=a[d]);this.isDirty=function(){var a,b,d=c(),e=!1;if(0<this.tg.deletedEntities().length)e=!0;else if(0<d.length&&
d[d.length-1].isDirty())e=!0;else for(a=0;a<d.length;a++)if(b=d[a],b.RowState()!==tg.RowState.UNCHANGED){e=!0;break}return e};this.isDirtyGraph=function(){var a,b,d=c();b=!1;if(0<this.tg.deletedEntities().length)b=!0;else if(0<d.length&&d[d.length-1].isDirty())b=!0;else for(a=0;a<d.length;a++)if(b=d[a],b.RowState()!==tg.RowState.UNCHANGED){b=!0;break}else if(b=b.isDirtyGraph(),!0===b)break;return b}};this.customize=function(a){b.push(a)}};b||(tg.generatedNamespace[a]=d);return d};
tg.exportSymbol("tg.defineCollection",tg.defineCollection);
tg.AjaxProvider=function(){var a=function(){};this.execute=function(c){var b=c.success||a,e=c.error||a;c=$.extend({cache:!1,contentType:"application/json; charset=utf-8;",dataType:"json",type:"GET"},c);c.success=function(a){b(a,c)};c.error=function(a){if(e)e(a.status,a.responseText,c);else tg.onError({code:a.status,message:a.responseText})};var d=c,f;var g=c.data;f=/\{([^\}]+)\}/g;f="string"===typeof g?void 0:c.url.replace(f,function(a,b){if(b in g)return ko.utils.unwrapObservable(g[b])});d.url=f;
c.data&&"GET"!==c.type&&(c.data=ko.toJSON(c.data));$.ajax(c)}};tg.dataProvider=new tg.AjaxProvider;
